### ISSUE TITLE
Some Digibooster modules don't play correctly

### ISSUE THREAD

**Issue by softwarefailure** [libxmp/libxmp#196] opened 2020-11-06 17:18 UTC
Check out the attached archive. The module in that archive doesn't play correctly with libxmp. The file `good.mp4` shows what it should sound like and the file `bad.mp4` shows what it currently sounds like with libxmp. The problems begin around 23 seconds into the song.
 
[digib.zip](https://github.com/cmatsuoka/libxmp/files/5502569/digib.zip)

**Comment by AliceLR** [comment] 2020-11-06 21:24
Current uneducated guess as to what's going on here is libxmp has a bug with `VENV` chunks (instrument volume envelopes) or a note off command or note cut effect. I will dig further into this when I have a chance.

**Comment by AliceLR** [comment] 2020-11-11 16:02
This line stinks to me: https://github.com/libxmp/libxmp/blob/master/src/loaders/dbm_load.c#L338

From experimentation the `VENV` chunk seems to be consistently 2 bytes plus 136 bytes per envelope long. Despite the [documentation claiming 134 bytes per envelope](https://github.com/libxmp/libxmp/blob/master/docs/formats/DigiBoosterPro.txt#L83), careful reading of the offsets in the document and checking the uploaded file suggests it's 136.

I haven't verified if that's the cause of this issue but it definitely seems like a good place to start.

**Comment by AliceLR** [comment] 2020-11-11 18:40
I wrote something to get a dump of the instruments and envelopes and I'm satisfied that they're being loaded correctly (aside from libxmp dropping the last point), but I noticed that some instruments have duplicate volume envelopes (for example, in this module, instrument 3 has 5 different envelopes). Since I can't open the volume envelopes in DigiBooster Pro without it crashing my VM, does it actually allow multiple envelopes per instrument, or are the first four junk? Instruments 1 and 2 also have duplicate envelopes.

```
:           : Instr. #  Enabled : (...)=Loop  [S]=Sustain
:           : --------  ------- : -------------------------
...
: V.Env. 03 : 3         Yes     :  0       8
:           :                   :  0       60
: V.Env. 04 : 3         Yes     :  0       5
:           :                   :  0       64
: V.Env. 05 : 3         Yes     :  0       3       8       23
:           :                   :  0       27      48      64
: V.Env. 06 : 3         Yes     :  0       4
:           :                   :  0       64
: V.Env. 07 : 3         Yes     :  0       1       11      34
:           :                   :  0       46      52      64
...
```

**Comment by softwarefailure** [comment] 2020-11-14 22:30
Thanks, the initial error is fixed now. But there's another playback error in the very same module. About 2 minutes and 32 seconds into the module there is suddenly some major instrument artefact that definitely shouldn't be there...

**Comment by AliceLR** [comment] 2020-11-14 22:41
I will look into that when I get a chance, thanks.

**Comment by AliceLR** [comment] 2020-11-16 03:43
Looks like that issue is due to `AF1` getting interpreted as a volume slide up by 15 instead of as a fine slide down by 1, which is fortunately a very easy fix.

**Comment by sezero** [comment] 2020-11-16 04:59
Are there any issues left with digibooster modules?

**Comment by sezero** [comment] 2020-11-17 07:10
All reported issues (and some more) are fixed in git/master: Closing.
If any other issues are found, please open a new bug entry.

**Closed by sezero** 2020-11-17 07:10 UTC
