### ISSUE TITLE
MOD file plays in slow motion?

### ISSUE THREAD

**Issue by HunterZ** [libxmp/libxmp#619] opened 2022-11-21 03:50 UTC
UltraX.mod seems to play in slow motion, with a listed duration of almost 40 minutes: https://modarchive.org/index.php?request=view_by_moduleid&query=58591

This is definitely incorrect behavior.

Edit: Sorry, probably should've filed this against libxmp? Let me know if I need to re-file it over there.

**Comment by sezero** [comment] 2022-11-21 04:01
@AliceLR: Any ideas?

**Comment by AliceLR** [comment] 2022-11-21 06:52
This is unfortunately a duplicate of #505. Thanks for the reminder, because this really needs to be fixed.

**Comment by sagamusix** [comment] 2023-03-12 11:01
I will close this duplicate issue. Feel free to subscribe to the related issue if you want to be notified of when this is fixed.

**Closed by sagamusix** 2023-03-12 11:01 UTC
Labels: mod
