### ISSUE TITLE
Unable the build libxmp-lite using cmake 

### ISSUE THREAD

**Issue by Lucas-Marcel** [libxmp/libxmp#620] opened 2022-11-22 21:40 UTC
CMake Error at CMakeLists.txt:8 (include):
  include could not find requested file:

    C:/Users/Windows.lite/Documents/libxmp-master/lite/cmake/libxmp-checks.cmake

**Comment by sezero** [comment] 2022-11-22 21:52
Looks like a duplicate of #502 and #596.

**Closed by sezero** 2022-11-22 21:52 UTC
