### ISSUE TITLE
Question, what's the relation with openmpt

### ISSUE THREAD

**Issue by ghost** [libxmp/libxmp#737] opened 2024-05-15 20:00 UTC
It seams that libxmp and libopenmpt are a deduplication of effort. Why you don't just merge? .

**Comment by AliceLR** [comment] 2024-05-15 22:32
* libxmp is an older library than libopenmpt (it was contemporary with its predecessor, Modplug Tracker).
* libxmp uses mostly clean ANSI C with a handful of widely supported extensions. libopenmpt is written in whatever the latest C++ edition is, which gives it a portability disadvantage (old toolchains can not compile it). If you are not familiar with these languages: when using them in "good practice", they do almost everything in completely different ways with completely different standard library functions, so their code is not especially compatible. Compiled C++ is also larger on average than its equivalent compiled C.
* libxmp and libopenmpt have software mixers which sound different. For example, libxmp has anti-click functionality and libopenmpt has volume ramping, which give their playback different characters.
* libxmp and libopenmpt have completely different internal organization and playercode, which give them different advantages as supporting different formats. For example, libxmp has much more accurate Farandole Composer playback than libopenmpt is capable of right now due to advantages in the the way libxmp was designed, and for the longest time libopenmpt couldn't handle MED synths.
* libxmp and libopenmpt use slightly different licenses.

For an example of a project that will probably never use libopenmpt by default: I fork libxmp into MegaZeux, which targets C99 and C++98 or C++11. I fork libxmp so I can trim down the binary size for resource limited platforms and throw out format loads I don't need. Forking libopenmpt into my source tree is simply not an option because it requires newer C++, and it provides nothing to allow me to whitelist formats/packers through the API (last I checked). My software is a game engine and *under no circumstance* will I ever allow formats like UMX, as supporting them is implicitly approving copyright violation. Also, I like libxmp's playback slightly more.

**Comment by sezero** [comment] 2024-05-15 22:40
Close this ?

**Comment by sagamusix** [comment] 2024-05-16 08:57
Monocultures are bad, even in open-source. OpenMPT has its own strenghts, as does libxmp. libxmp supports formats that I am not interested in, OpenMPT supports formats that libxmp devs are not interested in. For the formats supported by both, there is a lot of cross-pollination happening. There's a lot of things in libxmp I could probably not agree with the way they're done, and likewise there are probably a lot of things in OpenMPT that libxmp developers couldn't agree doing that way (the choice of language being the most obvious but there are many factors). It would be impossible to make one library that satisfies all contributors' preferences and opinions. libxmp is probably more realistic to use on exotic handheld hardware as Alice says, something that I am not particularly interested in so I don't want to waste my time on it. If another library is good at handling those platforms, it means I don't have to think about them.

Sincerely,
OpenMPT main developer and occasional libxmp (and other trackers and tracker libraries) contributor.

**Closed as completed** 2024-05-16 16:22 UTC
