### ISSUE TITLE
Mod plays extremely slow. 

### ISSUE THREAD

**Issue by LossyDragon** [libxmp/libxmp#505] opened 2021-12-22 00:18 UTC
When playing this mod, it plays extremely slow after the first pattern. 

Works fine in Milky and OpenMPT. 

I did play around with the file and removing the Set Tempo in the second pattern makes the module play fine based on a quick test. 

It also seems setting another Tempo anywhere causes it to play slow too. 

[CHAVEZ_-_Flowerpower.zip](https://github.com/libxmp/libxmp/files/7759022/CHAVEZ_-_Flowerpower.zip)

**Comment by sezero** [comment] 2021-12-22 02:41
@AliceLR ?

**Comment by AliceLR** [comment] 2021-12-22 03:33
libxmp will interpret `Fxx` where `xx`>0x20 as either speed or tempo depending on the detected tracker, so it's probably incorrectly IDing the tracker and using the wrong quirks (similar issue: #144). Given the difficulty of the problem and the current state of maintainer feedback I don't feel comfortable modifying the tracker ID algorithm, but this module *might* be a candidate for the "special module quirks" system in load_helpers.c.

**Comment by AliceLR** [comment] 2022-04-12 00:17
According to #modland logs, what OpenMPT (and apparently XMPlay) do for this is the following:

* Scan with CIA timing.
* If CIA timing produces a duration of >8 or 9 minutes, scan with VBlank.
* If the VBlank duration is less than CIA, use VBlank instead of CIA.

Something like this probably could be achieved with little modification outside of the MOD loader by implementing a lightweight scan (which it already *kind of* does, just not sequentially through the orders). It could probably be limited to just modules that detect as `TRACKER_NOISETRACKER`, `TRACKER_PROBABLY_NOISETRACKER`, and `TRACKER_SOUNDTRACKER`, which are the only ones libxmp currently applies VBlank timing to unconditionally. This would not intrude on the rest of the tracker detection routine and would be more robust than adding another module quirks hack.

**Comment by AliceLR** [comment] 2022-04-12 09:02
> I've marked some of them over the years: http://janeway.exotica.org.uk/search.php?what=0&special=&query=&cat=0&show=25&tags=2168&effects=&gfxstyles=&collection_category=0&collection=&year=all&soundformat=&bitplanes=0&gfxsize=0&country=&more=show

Thanks, I already found a pretty dumb bug by trying a couple of those long Jogeir modules. The copies of these from Kestra seem to work now (the ones on Modland are edited to use CIA timing though?):
```
mod_load [src/loaders/mod_load.c:858] Module title: "face another day"
mod_load [src/loaders/mod_load.c:858] Module type: Protracker M.K.
mod_load [src/loaders/mod_load.c:862] Stored samples: 31
compare_vblank_cia [src/loaders/mod_load.c:461] estimated VBlank: 1058820ms
compare_vblank_cia [src/loaders/mod_load.c:462] estimated CIA:    3618508ms
```
```
mod_load [src/loaders/mod_load.c:858] Module title: "guitar slinger"
mod_load [src/loaders/mod_load.c:858] Module type: Protracker M.K.
mod_load [src/loaders/mod_load.c:862] Stored samples: 31
compare_vblank_cia [src/loaders/mod_load.c:461] estimated VBlank: 300320ms
compare_vblank_cia [src/loaders/mod_load.c:462] estimated CIA:    572130ms
```

**Comment by AsleAMP** [comment] 2022-04-12 09:18
I can't vouch for modland material.
At least, the linked material on Kestra should be correct (replay-wise)

----- Mail original -----
De: "Alice R." ***@***.***>
À: "libxmp/libxmp" ***@***.***>
Cc: "AsleAMP" ***@***.***>, "Comment" ***@***.***>
Envoyé: Mardi 12 Avril 2022 11:03:08
Objet: Re: [libxmp/libxmp] Mod plays extremely slow.  (Issue #505)







I've marked some of them over the years: http://janeway.exotica.org.uk/search.php?what=0&special=&query=&cat=0&show=25&tags=2168&effects=&gfxstyles=&collection_category=0&collection=&year=all&soundformat=&bitplanes=0&gfxsize=0&country=&more=show 

Thanks, I already found a pretty dumb bug by trying a couple of those long Jogeir modules. The copies of these from Kestra seem to work now (the ones on Modland are edited to use CIA timing though?): mod_load [src/loaders/mod_load.c:858] Module title: "face another day"
mod_load [src/loaders/mod_load.c:858] Module type: Protracker M.K.
mod_load [src/loaders/mod_load.c:862] Stored samples: 31
compare_vblank_cia [src/loaders/mod_load.c:461] estimated VBlank: 1058820ms
compare_vblank_cia [src/loaders/mod_load.c:462] estimated CIA:    3618508ms mod_load [src/loaders/mod_load.c:858] Module title: "guitar slinger"
mod_load [src/loaders/mod_load.c:858] Module type: Protracker M.K.
mod_load [src/loaders/mod_load.c:862] Stored samples: 31
compare_vblank_cia [src/loaders/mod_load.c:461] estimated VBlank: 300320ms
compare_vblank_cia [src/loaders/mod_load.c:462] estimated CIA:    572130ms

**Comment by sagamusix** [comment] 2022-04-12 09:45
Here's my collection of VBlank test cases, which mostly consists of Jogeir mods: [vblank tests.zip](https://github.com/libxmp/libxmp/files/8471747/vblank.tests.zip)

**Comment by AliceLR** [comment] 2022-04-12 13:35
> Here's my collection of VBlank test cases, which mostly consists of Jogeir mods: [vblank tests.zip](https://github.com/libxmp/libxmp/files/8471747/vblank.tests.zip)

Thanks, going through these now... at least one of them detects as "Fast Tracker M.K." so I just dropped the ID requirement on this check entirely.
```
mod_load [src/loaders/mod_load.c:852] Module title: "crystal rain"
mod_load [src/loaders/mod_load.c:852] Module type: Fast Tracker M.K.
mod_load [src/loaders/mod_load.c:856] Stored samples: 31
compare_vblank_cia [src/loaders/mod_load.c:461] estimated VBlank: 222780ms
compare_vblank_cia [src/loaders/mod_load.c:462] estimated CIA:    795210ms
```

**Comment by AliceLR** [comment] 2022-04-13 00:02
Am I interpretting "the rebellion" correctly—it is supposed to actually be CIA, but relies on `F20` being a speed rather than a BPM? The first pattern doesn't make sense as VBlank...

**Comment by sagamusix** [comment] 2022-04-13 10:45
Yeah, it's a weird one. The first pattern plays way too slow due to that in OpenMPT but the rest plays correctly at least. I don't think this is the official rip, and it could be that someone just tried to be "helpful" sticking that `F7D` command in the first pattern. If you take the version from ModLand, it doesn't have that. It's probably just best to ignore the version from my zip file.

**Comment by AliceLR** [comment] 2022-04-15 03:49
> Yeah, it's a weird one. The first pattern plays way too slow due to that in OpenMPT but the rest plays correctly at least. I don't think this is the official rip, and it could be that someone just tried to be "helpful" sticking that `F7D` command in the first pattern. If you take the version from ModLand, it doesn't have that. It's probably just best to ignore the version from my zip file.

That's kind of what I was thinking—*maybe* if something like it comes up again there could be individual module detection for speed `F20` in CIA mode, but otherwise... just going to pretend I didn't see it.

I retooled this to be part of the scan because it was clear the imprecise timing was not sufficient to pick up some modules. Some of the ones on Kestra are really cutting close to the 8 minute limit. I also want to run libxmp's loader over all of the MODs I have from Modland to make sure nothing is getting its timing mode incorrectly flipped.

The specifics of how VBlank vs. CIA timing works though almost makes me wonder if there's any use in the approach of starting from VBlank and detecting CIA after instead of the reverse. The modules that libxmp incorrectly assigns VBlank to without this patch are 10-20 times longer in VBlank mode than they are in CIA due to "average" CIA `Fxx` values ~125 vs. speed 6 default. They could easily get clobbered if accompanied by speed effects, too, so maybe not...

Aforementioned module near the 8 minutes/480000ms limit I set to test with:
```
mod_load [src/loaders/mod_load.c:781] Module title: "3-part-introtune"
mod_load [src/loaders/mod_load.c:781] Module type: Protracker M.K.
mod_load [src/loaders/mod_load.c:785] Stored samples: 31
compare_vblank_scan [src/scan.c:635] CIA    487096ms
compare_vblank_scan [src/scan.c:636] VBlank 400660ms
```

**Comment by AliceLR** [comment] 2022-04-15 10:03
The threshold doesn't work for these VBlank modules. Aside from spring dreams and techdust they break mostly at the very end, and aren't that noticeable aside from loops breaking.
* [i'm all right.md by The Dark Knight](http://janeway.exotica.org.uk/release.php?id=46732) (CIA time 5m17s, -3s)
* [ledstorm by Jogeir](http://janeway.exotica.org.uk/release.php?id=32277) (2m24s, -16s)
* [mixified by Jogeir](http://janeway.exotica.org.uk/release.php?id=47992) (5m31s, -5s)
* [mystified by Jogeir](http://janeway.exotica.org.uk/release.php?id=32279) (3m56s, -16s)
* [overture by Jogeir](http://janeway.exotica.org.uk/release.php?id=32281) (5m28s, +33s)
* [spring dreams by WOTW](http://janeway.exotica.org.uk/release.php?id=88296) (3m56s, +1m42!!!) (Modland copy identical)
* [techdust by Hobbes](http://janeway.exotica.org.uk/release.php?id=32041) (2m17s, -2m06s!!!) (Modland copy identical)
* [the wanderer by Jogeir](http://janeway.exotica.org.uk/release.php?id=47996) (6m56s, -5s)
* [vapour highway by The Dark Knight](http://janeway.exotica.org.uk/release.php?id=46738) (6m58s, -14s)

The following modules may be miscategorized as VBlank or not clean:
* [Lonely Wolf by Dj Joge](http://janeway.exotica.org.uk/release.php?id=44458) blatantly uses `F7D` twice, once on the same row as a regular speed effect. The other usage adds 2.5 minutes to the module length.

spring dreams and techdust seem like good candidates for the module quirks list, anyway. Not sure how else they'd get picked up.

**Comment by AliceLR** [comment] 2022-04-16 22:00
The time check fixes about 200 CIA modules incorrectly assigned VBlank, from what I can tell. However, looking at the number of modules that use low range `Fxx` and high range `Fxx` on the same row, this is clearly not sufficient:
```
# CIA      : 11029
# VBlank   : 3804
```
I'm going to go through the "VBlank"  ones to see if any actually are. I hate this

**Comment by sagamusix** [comment] 2022-04-24 16:37
I wonder if not assuming VBlank at all if the Fxx parameter is sufficiently high (e.g. > 160 or so) would be sensible... that would fix techdust at least.

**Comment by sagamusix** [comment] 2022-04-24 17:07
https://modarchive.org/index.php?request=view_by_moduleid&query=189801 is another one of those unsolved cases that should be VBlank but aren't detected as such (at least in OpenMPT).

**Comment by AliceLR** [comment] 2022-04-24 22:20
> I wonder if not assuming VBlank at all if the Fxx parameter is sufficiently high (e.g. > 160 or so) would be sensible... that would fix techdust at least.

I'm not sure about that—I've seen a few that use `FFF` at the end to intentionally pad silence or pause. The high speed values in VBlank modules seem pretty arbitrary, especially when they're used for this purpose. (The real offenders wrt silence padding though are some CIA modules that use `E6F`+`EEF` because for *some* reason they needed 60 minutes of silence.)

I did get through the ~500 modules that all get IDed as VBlank due to tracker ID last week, my progress is mostly stalled for unrelated reasons. To summarize what I found (numbers slightly off because I haven't finished a second pass):

* ≈345 CIA modules incorrectly IDed as VBlank (out of 491). This is, IMO, enough to conclusively say the `M.K.` tracker ID routine should never be used to determine VBlank vs. CIA.
* 29 modules IDed as VBlank are actually VBlank and use VBlank high speeds in nontrivial ways. Scan compare fixes 15 of them, but 3 are re-broken by using same row low Fxx + high Fxx to prevent the scan compare (which is necessary, see below). The other 14 don't pass the time threshold. I've seen a lot of high speed values here, including `FFF`... unsurprisingly these are the ones that don't get caught by scan compare. Right now I'm assuming most of these 14 plus the 3 that break from the same row check will need to go in the MD5 list to avoid regression.
* 86 modules IDed as VBlank are *most likely VBlank* but only use VBlank high speeds near the end to pad silence or to slow down between notes during the ending. I *think* these can be pretty reliably picked up by marking anything sufficiently long that uses high Fxx only in the last two orders as VBlank and disabling scan compare, but I haven't checked to see how this affects modules *outside* of the ones already detected as VBlank.
* 24 modules IDed as VBlank actually use MED effects: usually `FFE` near the end, but also occasionally `FF1`/`FF3` retriggers and in one case an `FFF` note cut. Obviously these are broken either way... VBlank might be preferable for the `FFE` modules though.
* 8 modules play the same either way—the high Fxx is unreachable or it's `F7D` followed by a speed on the same row.

Scan compare results on modules previously IDed as CIA (using 8 minute threshold). These modules are mutually exclusive from the above group:

* 56 modules are correctly changed to VBlank. None of these have high Fxx and low Fxx on the same row.
* 29 modules are incorrectly changed to VBlank, but 28 of these use high Fxx and low Fxx on the same row. This check can be used to prevent scan compare for these modules. A small number of VBlank modules in the prior section *do* have high Fxx and low Fxx on the same row, but ehhh...

**Comment by sezero** [comment] 2023-01-10 20:01
@AliceLR: Any progress on this (and #619) ?

**Comment by AliceLR** [comment] 2023-01-13 22:31
I recently refamiliarized myself with my patch and the short version of why I haven't made progress on this is: I have to reevaluate all ~500 MODs again to take into account a promising fix for the modules that use VBlank speeds *only near the end*.

I should just get this over with already. I'm sorry for the repeated delays.

**Comment by AliceLR** [comment] 2023-03-06 21:14
Update on this: I've verified the following procedure has a very good success rate at correcting the MODs that were incorrectly tracker IDed as using VBlank timing. Two of the new rules increase the number of affected modules yet again, and while I'm still gathering data on these, they are also looking quite good. This is probably the final version of the testing procedure that will make it into the patch for this issue.

All numbers come from testing on the Protracker folder on Modland.

Definitions:
* "High Fxx"—an `F##` command where `##` is a value equal to or greater than `20h`.
* "Low Fxx"—an `F##` command where `##` is a value less than `20h`.

Timing identification procedure:

1. If there are no high Fxx commands anywhere in the module, timing is irrelevant. Stop testing.
2. Assume CIA timing initially.
    * This fixes 345 CIA modules that were originally tracker IDed as VBlank.
3. If a module has a verifiable Soundtracker or Noisetracker signature (currently only `M&K!` or `N.T.`), it is VBlank. Stop testing.
    * Modland has 66 `M&K!` MODs and no `N.T.` MODs; need to verify this is actually correct for those.
4. If a module, on *any* row in the module in *any* pattern, uses both high Fxx and low Fxx, it is CIA. Stop testing.
    * This test has a quite good success rate at filtering out CIA modules that would be incorrectly identified as VBlank by later steps, but also breaks a small number of VBlank modules.
5. Store the last used high Fxx command for each pattern into an array. If the following are true, it is VBlank. Stop testing.
    * The module is 8 or more orders in length.
    * The module does *not* use high Fxx in the first (length - 2) orders.
    * The module *does* use high Fxx in the last 2 orders.
    * The final instance of high Fxx in the module is **NOT** `F7D`.
    * This test re-fixes 86 of the 87 VBlank modules that were formerly tracker IDed as VBlank which only use high Fxx near the end. It also *additionally* makes ~387 new modules that were formerly tracker IDed as CIA now VBlank. For the vast majority of these, this is correct. A small handful of them change BPM and reset it to `F7D`, or were modified to add `F7D` so the modules would "work" in CIA-based players, hence the extra `F7D` rule. This check also fixes the Jogeir modules mentioned in previous comments.
6. If the module is in the module quirks (MD5) list, use whichever timing this list indicates.
7. If the module scan reports a module length of over 8 minutes (still assuming CIA), rescan the module with VBlank timing. Use whichever timing mode results in a shorter module length.
    * This re-fixes 12 of the 29 VBlank modules that were originally tracker IDed as VBlank which use high Fxx in nontrivial ways, fixes 56 additional VBlank modules that were originally tracker IDed as CIA, and breaks exactly one CIA module (after all of the other tests). Said CIA module uses F30+F1F to pad its ending length, and it never uses high Fxx and low Fxx on the same row. Oh well.

The other 17 VBlank modules that use nontrivial high Fxx—as well as possibly other VBlank modules from Saga Musix's pack after I'm done sifting through the new 387 modules—will need MD5s.

**Comment by AliceLR** [comment] 2023-03-10 20:06
I finished checking the 387 modules affected by step 5 above. This breaks *very few* unambiguously CIA modules and fixes quite a lot of VBlank and speed `F20` modules. It also "fixes" loops for other ambiguous modules, at a duration cost: some of these end up with *minutes* of silence at the end.

After talking again with Saga Musix it's clear that there are two other cases affecting these modules that may be affecting those "long" modules. Something may need to be done preemptively about these, but I'm comfortable submitting the routine as-is for now:
* ModPlug 1.16 and early OpenMPT player reset: these trackers would reset all playback parameters upon looping at the end (does not affect `Bxx`). Modules relying on this would probably use CIA `FFF` for a full pattern or more expecting a *short* silent pause at the end, but instead this turns into 5 minutes or more of silence with the new VBlank timing.
* ModEdit 2 speed clamp: this tracker clamps seems to clamp all speed values greater than `F1F` to either `F1F` or `F20` (haven't tested). I've only found one module unambiguously relying on this, and it isn't hurt very much by VBlank timing.

There's also just a handful of tampered or broken modules that this check affects.

**Comment by AliceLR** [comment] 2023-03-12 03:41
Re: marking "Noisetracker" signatures as VBlank, aside from it being obvious: there was exactly one His Master's Noise module with a high `Fxx` effect, and it is handled by the His Master's Noise loader. I updated the patch to add `QUIRK_NOBPM` to that loader as well.

I went through the existing module quirks list, and assuming these five modules are in the list ONLY because of VBlank/CIA timing (@cmatsuoka?), they can be removed by this patch:
* `ALF (SE)/no-mercy.mod`: this is now fixed by always assuming CIA initially, but for good measure, it also has high and low `Fxx` on the same row.
* `mod.siedler ii`: this is now fixed by the scan compare.
* `klisje_paa_klisje.mod`: this is now fixed by the scan compare.
* `nebulos.mod`: this is now fixed by the scan compare. I was not able to locate the exact MD5 the quirk entry uses.
* `ode2ptk.mod`: this is now fixed by always assuming CIA initially, but for good measure, it also has high and low `Fxx` on the same row.

**Comment by sagamusix** [comment] 2023-03-12 19:46
no-mercy is definitely a very quirky module that needs proper emulatioon of some ProTracker quirks, so you may want to double-check that nothing breaks with that module when removing it from the quirks list.

**Comment by AliceLR** [comment] 2023-03-12 21:25
> no-mercy is definitely a very quirky module that needs proper emulation of some ProTracker quirks, so you may want to double-check that nothing breaks (in particular those piano chords triggered with implicit 9xx offsets) with that module when removing it from the quirks list.

I didn't fully check that one, thanks. I'll double-check klisje paa klisje and nebulos again too.

**Comment by AliceLR** [comment] 2023-03-14 08:09
klisje paa klisje is detected as "Converted M.K.", which in this case behaves more or less entirely like NoiseTracker mode. nebulos is detected as "NoiseTracker M.K.". The two most likely modes they'd get reassigned to with tracker ID changes are "Unknown" (roughly equivalent to `-emod`) and Protracker (equivalent to `-eprotracker`), which only result in minor period clamping and vibrato phase differences (respectively). I think these are okay to comment out.

siedler ii has a M!K! signature so its detection as Protracker ought to be safe.

**Comment by sagamusix** [comment] 2023-03-15 20:54
> siedler ii has a M!K! signature so its detection as Protracker ought to be safe.

Just a side note as I'm not sure how strictly to interpret the "ought to be safe": OpenMPT (and probably also trackers) also writes the M!K! signature for 4-channel MODs with more than 64 patterns. IIRC ProTracker has issues loading such modules otherwise.

**Comment by AliceLR** [comment] 2023-03-15 22:15
> Just a side note as I'm not sure how strictly to interpret the "ought to be safe": OpenMPT (and probably also trackers) also writes the M!K! signature for 4-channel MODs with more than 64 patterns. IIRC ProTracker has issues loading such modules otherwise.

Oh, interesting. libxmp *does* apply Protracker quirks to OpenMPT .MODs, so I don't think that would cause any further issues in this case.

**Comment by sagamusix** [comment] 2023-03-15 22:16
Yeah, it shouldn't make much of a difference. By the time that change was made, a handful of ProTracker quirks were already implemented, so PT-like playback should be fine.

**Closed** 2023-05-24 20:30 UTC
Labels: mod
