### ISSUE TITLE
Digital Symphony findings

### ISSUE THREAD

**Issue by sagamusix** [libxmp/libxmp#347] opened 2021-04-13 19:20 UTC
As mentioned in a PR, I have just finished writing my own [feature-complete Digital Symphony loader](https://github.com/OpenMPT/openmpt/blob/master/soundlib/Load_dsym.cpp) for OpenMPT.

Based on a quick glance, the xmp loader needs to address at least the following issues to be able to load more files (and play them):
- Missing support for sigma-delta compression. Feel free to take the decoder from OpenMPT.
- Missing support for several other non-compressed sample formats that xmp already supports, so adding them should be trivial.
- Several pattern commands are not imported even though xmp should be able to support them (e.g. panning). I couldn't find any real-world modules using effects 0x2B and 0x32 yet but they are implemented in OpenMPT the way I think they should work.
- Suggested sanity checks: bail out early if number of channels is 0, or if there are more than 4096 tracks / orders.
- Supposedly patterns / tracks are grouped into chunks of 2000 tracks (i.e. chunks of 512000 uncompressed bytes), but I have no modules to verify this.
- There's two files with a questionable LZW stream [this collection](https://archive.org/details/zenta-digital-symphony-collection-102) (FULLEFFECT and NARCOSIS) that my code originally didn't load; xmp also doesn't load them but I didn't verify whether it's for the same reason. TimPlayer's LZW routines get these files wrong, too. They require a special case to load correctly to not increase the bit width once the decompressed data has reached the expected size (the last insertion into the dictionary causes it to grow to 512 entries, so the bit width should be increased from 9 to 10, but if you do that, the next thing you read will be 769 instead of the expected 257). I have added that special handling to OpenMPT and the files load fine now; and while it smells like a bug in the LZW encoder to me, all the other 3000+ files are unaffected by the fix, so I think it's safe.

**Comment by AliceLR** [comment] 2021-04-13 23:26
Thanks for the detailed followup on this! I will take a look at the sample-related issues at some point—I've been sitting on a huge collection of Digital Symphony modules from ADPL that I haven't been able to do anything with, so I'll check for more of the unusual LZW streams when I get to it. (Since libxmp's Digital Symphony loader currently relies on pulling in a very old and questionable LGPL LZW decoder it might be worthwhile to entirely replace it while I'm at it.)

**Comment by sagamusix** [comment] 2021-04-14 07:09
From my unterstanding, that LZW decoder was actually GPL, not LGPL, 
which would have implications for xmp's license as well (unless Claudio 
got permissiong to relicense it under the LGPL). I wrote a very compact 
LZW decoder for OpenMPT (optimized just for DSym and nothing else), so 
you can take that one as well. It should still be easy to extend it to 
support other formats with other bit widths etc. if required.

Can you give a link to that collection you found? The more modules I can 
test my stuff against, the better.

**Comment by AliceLR** [comment] 2021-04-14 07:41
Re: the LZW decoder license, `readlzw.c` directs to `unarc.c` which has the LGPL 2.1 boilerplate on it. It appears to have been relicensed in 2012. That said, the vast majority of libxmp is MIT license so it seems like there's been a deliberate effort towards moving toward a permissive license. The remaining LGPL code is fmopl.c, which can be replaced with a patched Opal if anything ever uses it again; the depackers; some old loaders that are not currently enabled; and the Digital Symphony loader indirectly via its dependency on readlzw.c. With `LIBXMP_NO_DEPACKERS` the only one of those linked in is that LZW decoder. (Unless ProWizard is LGPL; its licensing situation isn't clear to me.)

The ADPL Digital Symphony library is [here](http://www.apdl.org.uk/apdlpd/library/symphony.htm), but there isn't a mass download link. I think I ended up having to automate downloading individual modules.

**Comment by sagamusix** [comment] 2021-04-14 17:16
> Re: the LZW decoder license, readlzw.c directs to unarc.c which has the LGPL 2.1 boilerplate on it. It appears to have been relicensed in 2012.

Ah, that indeed seems to be the case. I traced back readlzw.c to its original package, where I found the GPL license instead. Moving to OpenMPT's or any other from-scratch LZW decoder might be the way to go here for a more permissive license.

> The APDL Digital Symphony library (...)

Seems like most, if not all of that stuff is also in the collection I linked in the first post. Guess I'll do a recursive wget to compare. ;)

**Comment by AliceLR** [comment] 2021-07-25 11:37
I replaced the LZW decoder for Digital Symphony, fixing bugs loading modules with the EOF quirk and fixing the loader as a whole when the input stream isn't backed by a `FILE`. I have a partial patch for the uncompressed 8-bit/16-bit sample formats I split off the LZW patch, and I've looked at the sigma-delta decoder you mentioned, so those will probably be the next things that get patched.

**Comment by AliceLR** [comment] 2021-07-30 02:44
This wasn't mentioned here, but #463 fixes another bug in libxmp's Digital Symphony loader, which is that the info text wasn't being read.

**Comment by AliceLR** [comment] 2021-10-12 04:41
Useless data re: sample formats from the APDL modules, now that I can:
```
Total:			4010
Log:			2065
LZW:			3464
Linear 8-bit:		0
Linear 16-bit:		0
Sigma-delta linear:	2606
Sigma-delta log:	4
```

@sagamusix do you have any examples of modules that use the uncompressed linear formats? The only place I've seen them cited is a data file from file(1). (I haven't done any testing with Digital Symphony itself yet and I don't really have a setup for it.)

**Comment by sagamusix** [comment] 2021-10-12 18:17
I thought that I had some files in each format but it doesn't seem to be the case.

**Comment by AliceLR** [comment] 2021-10-29 22:11
> > and change the loops to sustain loops
> 
> FWIW, this is what OpenMPT is doing in several formats. For all intents and purposes, a sample loop should be treated like IT's sustain loops if it can be released. (XM's key-off only releases envelopes though on second though, so the only way to emulate this with existing commands is IT's note-off, I think). There are several other formats that support this, like X-Tracker DMF.

The obstacle here/why I didn't use a sustain loop even though it's probably technically correct is currently libxmp requires that the *entire* sample structure and sample data be duplicated, possibly so BIDI loops and sustain loops can be unrolled independently. I'm about 99% certain this is part of why Claudio keeps mentioning that libxmp needs real BIDI loop support (and IMO loop unrolling if done at all should be kept in temporary buffers that can be invalidated during state changes or invert loop).

An option I considered is making it so a sustain loop without a regular loop doesn't require the duplication, but it looked potentially messier than just adding a new effect and sample flag.

**Comment by AliceLR** [comment] 2021-10-29 22:29
> libxmp requires that the _entire_ sample structure and sample data be duplicated, possibly so bidi loops and sustain loops can be unrolled independently. I'm about 99% certain this is part of why Claudio keeps mentioning that libxmp needs real bidi loop support.

You know what? This is going to suck but I'll just fix the stupid bidi loops once some of the other open PRs are resolved.

**Comment by AliceLR** [comment] 2021-10-30 07:15
> You know what? This is going to suck but I'll just fix the stupid bidi loops once some of the other open PRs are resolved.

🙄https://github.com/libxmp/libxmp/compare/master...AliceLR:fix-bidi

Currently still a trash fire and several tests are broken, but at least it "seems" to work.

**Comment by AliceLR** [comment] 2021-10-31 04:22
After going through the tests that fail due to the bidi loop patch, here's what I found.

Tests where the mixer output data is too incomprehensible to determine anything useful (very small bidi loops):
```
test 355: test_openmpt_xm_arpeggioclamp: at compare_mixer_data.c:71: position mismatch: **fail**
test 373: test_openmpt_xm_notelimit2: at compare_mixer_data.c:71: position mismatch: **fail**
test 455: test_openmpt_it_wnoteoff: at compare_mixer_data.c:71: position mismatch: **fail**
```
Tests where the mixer output is mainly off during the reverse portion of the loop (due to the old output reporting unrolled positions and the new output reporting the estimated real position). However, some reported positions on subsequent forward sections of the loop are *slightly* off (one or two positions), so there might be something that needs fixing here.
```
test 357: test_openmpt_xm_delay1: at compare_mixer_data.c:71: position mismatch: **fail**
test 365: test_openmpt_xm_envretrig: at compare_mixer_data.c:71: position mismatch: **fail**
test 374: test_openmpt_xm_noteoff: at compare_mixer_data.c:71: position mismatch: **fail**
test 389: test_openmpt_xm_pickup: at compare_mixer_data.c:71: position mismatch: **fail**
test 401: test_openmpt_it_bidi_loops: at compare_mixer_data.c:71: position mismatch: **fail**
```

Going to compare PCM output between master and my patch to see what's still wrong here (if anything).

Tests 401 and 455 are interesting because, after I did some manual tweaking to fix support for this quirk, libxmp is now somehow tuned closer to the Impulse Tracker reference sample than OpenMPT is (does OpenMPT not shorten the reverse section of the bidi loop by 1 sample on import? Bidi-Loops.it seems to have the same problem).

was this issue about something besides bidi loops? i feel like i'm forgetting something

**Comment by sagamusix** [comment] 2021-10-31 11:57
> Tests 401 and 455 are interesting because, after I did some manual tweaking to fix support for this quirk, libxmp is now somehow tuned closer to the Impulse Tracker reference sample than OpenMPT is (does OpenMPT not shorten the reverse section of the bidi loop by 1 sample on import? Bidi-Loops.it seems to have the same problem).

OpenMPT does shorten bidi loops by one sample, but during playback. There seems to be a one-sample offset compared to Impulse Tracker, but the loop length itself is correct (e.g. a 64-sample bidirectional loop effectively turns into a 127-sample unidirectional loop).

> was this issue about something besides bidi loops? i feel like i'm forgetting something

Yeah, Bidi-Loops.it was testing exactly that :) https://wiki.openmpt.org/Development:_Test_Cases/IT#Bidi-Loops.it

**Comment by AliceLR** [comment] 2021-10-31 12:02
On further review I was wrong about Bidi-Loops.it being affected and I edited that portion out just before you posted... whoops. wnoteoff.it still sounds off and spectrum analysis in Audacity confirms I'm not wrong about that one, at least.

I compared the three modules where the loops were too short to determine the cause of the voice positions drifting and got this. For some reason they didn't think to add decimal frequencies or note+cents to the output, so this is of questionable accuracy.

```
test 355: test_openmpt_xm_arpeggioclamp: at compare_mixer_data.c:71: position mismatch: **fail**
	master: 417Hz
	patch: 414Hz
	reference: 415Hz

test 373: test_openmpt_xm_notelimit2: at compare_mixer_data.c:71: position mismatch: **fail**
	master: 460Hz
	patch: 457Hz
	reference: 459Hz

test 455: test_openmpt_it_wnoteoff: at compare_mixer_data.c:71: position mismatch: **fail**
	master:		709Hz
	patch:		710Hz
	reference:	709Hz
	OpenMPT:	701Hz
```

**Comment by sagamusix** [comment] 2021-10-31 12:39
> does OpenMPT not shorten the reverse section of the bidi loop by 1 sample on import?

I just had another look at that code and the way it computes how much it overshot the loop end was very convoluted and caused some minor differences. I think I'll have to rewrite that code...

**Comment by AliceLR** [comment] 2021-10-31 14:58
The drift in bidi.it was caused by using the modified `vi->end` to derive the start of the reverse loop. With that fixed I've found a new problem, which is that for some reason at the end of a tick the mixer will add the equivalent of a single output sample to the voice position. I don't know why it does this but it causes the two samples to slowly drift due to the bidi sample ending at the same time as the end of a tick more frequently. Removing this fixes it and doesn't seem to break anything audibly, but instead it breaks an additional 50 tests. :(

**Comment by AliceLR** [comment] 2021-12-22 17:12
Just realized I am dumb and the libxmp mixer fixed point uses a signed int fraction and floor rounding, so negative step values should just work with no required modification whatsoever. The cached reverse sample I was trying to do before is totally pointless!

**Closed** 2022-02-23 15:15 UTC
Labels: bug
